### ISSUE TITLE
USER STORY: Register for site

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#12]
As a **User** I can **register to the blog** so that **I can create my own profile, blog posts and comments**.
***
**Acceptance Criteria**:
- [x] **1. Given** that I am an unregistered user, **when** I am on the blog's home page I can see a 'Register' button so that when I click on it, **then** I am redirected to a page to enter my details to register to the site.
- [ ] **2. Given** that I am a registered user, **when** I click on my profile I can see a button that says 'Create Post' and **then** I can click on the button and I am directed to a page to be able to create my own post.
- [ ] **3. Given** that I am a registered user, **when** I am logged in **then** I can no longer see the 'Register' link in the navbar.
***
**Tasks**:
- [x] Create a register page
- [x] Create link in navbar to direct users to register
- [x] Use the Django User model to add user profiles to the database
- [ ] Create button to create posts on user's profile page
- [ ] Hide register button once user is registered and logged in
### Epic:  #3

**Comment by mariam138** [comment]
- May need splitting down into smaller user stories as creating the profile and allowing registration seem to be two different functions.

**Comment by mariam138** [comment]
Archived as a new version of this issue has been created to remove the 'Create Posts' aspect.
