### ISSUE TITLE
USER STORY: Log into site

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#13]
As a **User** I can **Log in to the blog** so that **I can comment and create posts to share**.
***
**Acceptance Criteria**:
- [x] **1. Given** that I am not logged in, **when** I navigate to the home page of the blog **then** I can click on the 'Log In' button to log in using my account details.
- [x] **2. Given** that I am logged in, **when** I am navigated to the home page **then** I can no longer see the 'Log In' button and **then** I can see the 'Log Out' button instead.
***
**Tasks**:
- [x] Create sign-in page
- [x] Redirect user to home page once logged in
- [x] Hide 'Log In' button
- [x] Show 'Log Out' button

### Epic: #3
