### ISSUE TITLE
USER STORY: Log Out of Site

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#14]
As a **User** I can **log out of the website** so that **I can prevent anyone unauthorised from doing things on my account**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am a registered user **when** I am logged in **then** I can see a button that says 'Log Out'.
- [x] **2.** **Given**  that I am a logged in user **when** I click on the 'Log Out' button **then** then I am asked to confirm my action before logging out.
- [x] **3.** **Given** that I am a logged in user **when** I confirm my action of logging out **then** I am redirected back to the home page and can once again see the 'Sign Up' and 'Log In' buttons.
***
**Tasks**:
- [x] Make 'Log Out' button visible when user is logged in
- [x] Redirect to page confirming log out action when button is pressed
- [x] Show 'Sign Up' and 'Log In' buttons once user is signed out.
- [x] Style log out page to match base template

### Epic: #3
