### ISSUE TITLE
USER STORY: Sign Up with Social Media

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#15]
As a **User** I can **sign up to the site using my social media accounts** so that **I can access user content more quickly and don't have to remember another set of credentials**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** that I am an unregistered user, **when** I click the sign-up button **then** I am given a choice to sign up using Facebook, Twitter/X, Instagram and Google.
- [ ] **2.** **Given** that I am an unregistered user, **when** I click on my desired social media to sign up with, **then** I am redirected to a page confirming my action of signing up to the site with my given social media account.
- [ ] **3.** **Given** that I am using my social media to sign up to the site, **when** I confirm the action to sign up **then** my profile has automatically been created for me and **then** I am redirected back to the home page.
- [ ] **4.** **Given** that I have signed up using my social media account, **then** I am able to create my own posts or comment on other blog posts.
***
**Tasks**:
- [ ] Allow social media sign up with Django's AllAuth
- [ ] Create a user profile with the social media account information
- [ ] Give the same access permissions as users who registered with their own credentials
