### ISSUE TITLE
USER STORY: Create User Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#16]
As a **User** I can **have my profile created for me upon signing up** so that **I can show others who I am and connect with people who have similar interests to me**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am an unregistered user, **when** I sign up to the blog **then** my profile is created.
***
**Tasks**:
- [x] Create a Profile model
- [x] Information that user inputs when signing up is then sent to the database with this model

***
