### ISSUE TITLE
USER STORY: View User Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#17]
As a **User** I can **view my own profile** so that **I can see how others view my profile on the blog**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user, **when** I am logged in **then** I am able to click on the 'My Profile' link to see my profile.
- [x] **2.** **When** I am on the 'My Profile' page, **then** I am able to see what information is hidden from others and what is displayed to others.
***
**Tasks**:
- [x] Create a 'My Profile' page
- [x] Create link in navbar to the 'My Profile' page
- [x] Display the user's information such as: name, email, profile picture, bio, etc.
- [x] When viewing their own profile, highlight which fields are not seen by others
