### ISSUE TITLE
USER STORY: Edit User Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#18]
As a **User** I can **edit my profile** so that **I can change and update the information displayed to others**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user, **when** I am on the 'My Profile' page **then** an 'Edit' button is visible underneath my profile.
- [x] **2.** **When** I click the 'Edit' button, **then** I am able to change the information on my profile.
- [x] **3.** **When** I am done updating my profile, **then** I can click on a 'Save Changes' button to update my profile.
- [x] **4.** **When** I save my changes, **then** I get a message telling me the changes were successful.
- [x] **5.** If I have changed my mind on updating my profile **when** I click the 'Cancel' button, **then** I am able to discard any changes made.
***
**Tasks**:
- [x] Create 'Edit' button on profile page underneath profile
- [x] Create 'Cancel' button on profile page underneath profile which appears only when editing
- [x] When changes are saved, update the data in the database
- [x] When 'cancel' is pressed, create a modal that will ask them to confirm discarding the changes
- [x] If the user confirms discarding the changes, display the profile as it was before 'Edit' was pressed
- [x] Display success message when changes have been saved
- [x] Create 'Back' button on edit_profile page
- [x] Add summernote to 'Bio' field on client side

**Comment by mariam138** [comment]
Updated to remove acceptance criteria for uploading a profile picture to create a separate user story (#63)
