### ISSUE TITLE
USER STORY: Delete User Account

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#19]
As a **User** I can **delete my account** so that **my information and blog posts are deleted from the blog at my own request**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am a registered user, **when** I view my profile **then** the option to delete my account is present.
- [x] **2.** **When** I click to delete my account, **then** I am asked to confirm this action.
- [x] **3.** **When** I confirm the action of deleting my account, **then** my profile and any related posts are deleted.
- [x] **4.** **Then** I am given a message that my account deletion has been successful.
- [x] **5.** **Given** that I have deleted my account, **when** I click to sign in **then** my credentials do not work and I am not able to access my profile.

**Tasks**:
- [x] Create 'delete account' link/button on user's profile
- [x] Create modal pop up that shows when button is pressed to confirm action
- [x] If user confirms action, delete user data from database
- [x] Redirect user to home page
- [x] Show message to user on home page that deletion was successful
