### ISSUE TITLE
USER STORY: User Reset Password

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#20]
As a **User** I can **reset my password** so that **I can still access my account even if I forget my password to log in**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am a registered user, **when** I attempt to sign into my account **then** I am able to view an option for when I have forgotten my password.
- [ ] **2.** **Given** I am a registered user, **when** I click that I have forgotten my password **then** a link to reset my password is sent to my email.
- [ ] **3.** **Given** I have forgotten my password, **when** I click the link sent to my e-mail **then** I am redirected to a page that allows me to reset my password.
- [ ] **4.** **Given** I have forgotten my password, **when** I have reset my password with the link provided **then** I can sign in with my new password I have created.
**Tasks**:
- [ ] Add a 'Forgot password' link to the sign in page
- [ ] Redirect to a new page that allows user to enter the email they signed up with
- [ ] Verify that the email is in the database
- [ ] Send a link to the email that allows the user to reset their password
- [ ] Once password has been reset, update this in the database
- [ ] Redirect user back to sign in page
