### ISSUE TITLE
USER STORY: Create Travel Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#22]
As a **User** I can **create my own travel posts** so that **I can share my stories with others**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user, **when** I am signed in **then** I am able to create my own posts.
- [x] **2.** **Given** that I am signed in, **when** I click the 'Create Post' button/link **then** I am redirected to a new page where I can upload my blog content.
- [x] **3.** **When** I save the post as a 'Draft' **then** I can save my work and come back to finish it at a later time without it being published first.
- [x] **4.** **When** I click to publish the post **then** my post is saved and waiting for approval by admin before being visible to everyone else.
- [x] **5.** **When** the post has been approved, **then** my post is made visible for others to see.
- [x] **6.** If I change my mind while creating a blog post and don't want to save it as a draft, **when** I click 'Cancel' **then** I am asked to confirm my action.
- [x] **7.** **When** I confirm my action, **then** I am redirected back to the home page.
- [x] **8.** **Then** a message is displayed telling me my post was not saved.
***
**Tasks**:
- [x] Create 'Post' model
- [x] Create button/link for signed in users to redirect them to a page to create posts.
- [x] Create a page that includes editor for making posts.
- [x] Install summernote package for editing the post content
- [x] Create options to save post as a 'draft' or as 'published'
- [x] Save post to database when 'Save' is clicked
- [x] Create view for posting only when user is logged in
- [x] Create URL path for creating a post
- [x] Link URL to navbar link for 'Create post'
- [x] Create message for user telling them the post is awaiting approval.
- [x] Create modal when 'Cancel' is clicked asking user to confirm actions
- [x] When 'Cancel' is clicked, redirect user to homepage
- [x] If redirected back to homepage, display message saying post wasn't saved.
- [x] If 'Keep editing' is clicked, dismiss modal.
