### ISSUE TITLE
USER STORY: Read Blog Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#23]
As a **User** I can **read mine and other user's blog posts** so that **I can read mine and other people's travelling experiences**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am visiting the website, **when** I click on a post **then** I am able to view the full post on a separate page.
***
**Tasks**:
- [x] Create summary cards for each post
- [x] Create template to display full blog post on a separate page
- [x] Create url for detailed posts
- [x] Create view for displaying detailed post
- [x] Link each summary card to respective detailed post

**Comment by mariam138** [comment]
Update: add further tasks for user story
