### ISSUE TITLE
USER STORY: Edit User Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#24]
As a **User/Site Admin** I can **edit my own blog posts** so that **I can update my content and keep it fresh**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am a registered user, **when** I click to view my own post **then** I have the option to edit my post.
- [x] **2.** **Given** that I am a registered user, **when** I edit my post **then** I can save my changes and **then** these changes are reflected on the published post.
- [x] **3.** **Given** that I am updating my own post, **when** I have saved my changes **then** I am shown a message that the changes were successful.
***
**Tasks**:
- [x] Show edit button on user's own posts
- [x] Save changes to the database so the changes can be reflected in the post also
- [x] Create 'Cancel' button if user changes their mind on editing post
- [x] Show success message when post is changed
- [x] show message that post was not changed if 'Cancel' is pressed
