### ISSUE TITLE
USER STORY: Delete User Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#25]
As a **User/Site Admin** I can **delete my posts** so that **I can remove my content from the site if I wish to do so**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am a registered user **when** I view my own posts **then** I have the ability to delete the post.
- [x] **2.** **Given** that I am viewing my own post, **when** I delete my post **then** I am asked to confirm my action.
- [x] **3.** **Given** that I am deleting my own post, **when** I confirm my action of deleting **then** I receive a message to say my deletion was successful.
***
**Tasks**:
- [x] Create button to delete user's own post
- [x] Create modal to confirm the user's actions
- [x] Display a success/error message after action is confirmed.
