### ISSUE TITLE
USER STORY: Share Posts on Social Media

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#26]
As a **User/Site Admin** I can **share links to posts I have created/liked** so that **I can share my/others travelling experiences to a wider audience**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am a visitor, **when** I read a post that I like **then** I have the ability to share the post to my social media accounts.
- [ ] **2.** **Given** that I am a user, **when** I create a post **then** I have the ability to share the post to my social media
- [ ] **3.** **Given** that I am sharing a post to social media, **when** I click on the link to share **then** I can copy the link to the blog and paste it on any other social media websites.
- [ ] **4.** **Given** that I am sharing a post to social media, **when** I click on the link to share **then** I can choose which social media platform I want to share the post to and **then** the shared post is pre-populated for me.
***
**Tasks**:
- [ ] Add share icon to bottom of post so when clicked a modal pops up
- [ ] Have the blog's URL in the modal to copy
- [ ] Include social media icons in modal
- [ ] When icons are clicked, create a pre-populated message on that SNS page with link to blog
