### ISSUE TITLE
USER STORY: Search Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#27]
As a **User/Site Admin** I can **search for posts** so that **I can more quickly find posts that I'm interested in**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** that I am a user, **when** I am on the site **then** there is a search bar present.
- [ ] **2.** **Given** that I am a user, **when** I enter words into the search bar and click 'Search' **then** I am shown posts which are related to the term I entered in the search bar.
***
**Tasks**:
- [ ] Create a search bar in the navbar
- [ ] Allow searches by keywords - countries, travel tips, etc
- [ ] Display paginated page of posts which have that search term in the post
- [ ] Create template to show paginated posts (if not already created)

**Comment by mariam138** [comment]
Newer version of this issue has been created.
