### ISSUE TITLE
USER STORY: Group Posts by Country/Region

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#28]
As a **Site Admin** I can **group posts by their Country/Region** so that **the User can quickly find travel posts about a country/region of their interest**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that I am a User **when** I am searching the site **then** I can choose to select a country/region which **then** shows me a list of posts related to that country/region.
***
**Tasks**:
- [x] Create a link in the navbar for 'Country/Region'
- [x] Make link a drop down menu which lists the separate countries/regions
- [x] Make each country/region a separate link
- [x] Make each link direct the user to a page which shows posts about said country/region
