### ISSUE TITLE
USER STORY: View Paginated List of Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#29]
As a **User** I can **view a paginated list of posts** so that **I can easily select which post I want to view**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** there is more than one post in the database, **when** a user searches for a post **then** the posts are listed on a page.
- [x] **2.** **Given** there are multiple posts in the database, **when** searching for a post **then** the posts are listed with pagination for easier navigation.
***
**Tasks**:
- [x] Create fixtures to quickly populate database
- [x] Create template to list posts in a paginated fashion
- [x] If not on the first/last page of the search, include 'Next' and 'Back' buttons
- [x] Hide the 'Back' button on the first page
- [x] Hide the 'Next' button on the last page

**Comment by mariam138** [comment]
- Changed from 2 to 4 story points in anticipation of more effort required for this user story.

**Comment by mariam138** [comment]
- Remove the task related to creating searches to make this a separate user story
