### ISSUE TITLE
USER STORY: Search posts by likes

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#30]
As a **User** I can **search posts based on their likes ** so that **I can read posts based on their popularity**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** that posts can be liked, **when** searching for posts **then** posts can be filtered by the number of likes and **then** these posts are displayed to the user
***
**Tasks**:
- [ ] Add filter to search by number of likes
- [ ] Display posts based on number of likes
