### ISSUE TITLE
USER STORY: Display most popular posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#31]
As a **User** I can **view the most popular posts** so that **I can see what is trending in the travel community**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** that there are multiple posts **when** a user navigates to the home page **then** a list of the most popular posts are displayed
- [ ] **2.** **Given** that posts can be liked **when** the number of likes are above a certain number **then** that particular post will be displayed on the home page
***
**Tasks**:
- [ ] Allow posts to be liked (if not already done so)
- [ ] Allow a certain number of posts to be displayed on the home page
- [ ] Allow these posts to be displayed if they have a certain number of likes
- [ ] Display posts in descending order of likes
