### ISSUE TITLE
USER STORY: Display posts by most recently updated

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#32]
As a **User** I can **view the most recent posts** so that **I can view fresh content and stay up-to-date**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** there are multiple post **when** on the home page **then** the most recently updated posts are displayed.
***
**Tasks**:
- [ ] Display set number of posts on the home page
- [ ] Display posts in descending order of most recently updated/created
- [ ] Ensure this is automatically updated when newer posts are created
