### ISSUE TITLE
USER STORY: Create Admin Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#33]
As a **Site Admin** I can **create my own profile** so that **visitors of the blog can get to know me and my reasons why I created the blog**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am the Site Admin **when** the superuser is created **then** the profile for the superuser is also created.
***
**Tasks**:
- [x] Create a profile with the Profile model
- [x] Use the information submitted for the superuser to set up the basic profile
