### ISSUE TITLE
USER STORY: View Admin Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#34]
As a **Site Admin** I can **view my own profile** so that **I can see what information about myself is being shared with others**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that my profile has been created, **when** I click on the link to take me to my profile  **then** I can see what information is being shown.
***
**Tasks**:
- [x] Create a profile page template
- [x] Input the superuser profile information into the template
- [x] Create a link to view the profile when logged in
