### ISSUE TITLE
USER STORY: Edit Admin Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#35]
As a **Site Admin** I can **edit my profile** so that **I can tailor the information I am sharing to others**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a site admin **when** I view my profile **then** I have the option to edit my profile.
- [x] **2.** **Given** that I am editing my profile **when** I click 'Save' **then** I am shown a message that the save was successful/unsuccessful
***
**Tasks**:
- [x] Create edit button on profile
- [x] Allow changes to be made to profile
- [x] Show alert message when changes are saved
- [x] Show alert message if there was a problem saving the changes
