### ISSUE TITLE
USER STORY: Deactivate Admin Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#36]
As a **Site Admin** I can **deactivate my profile** so that **I can take a break from the blog if I desire without deleting my account**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am the site admin **when** I view my profile **then** there is the option to deactivate my account.
- [ ] **2.** **Given** I am deactivating my account **when** I click to deactivate **then** I am asked to confirm my choice of deactivation.
- [ ] **3.** **Given** I am deactivating my account **when** I confirm my action **then** a message is displayed that my deactivation was successful.
***
**Tasks**:
- [ ] Create deactivate button on the admin profile
- [ ] Allow modal to appear when button is clicked asking to confirm the decision
- [ ] If confirmed, log user out and show success message
