### ISSUE TITLE
USER STORY: Reactivate Admin Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#37]
As a **Site Admin** I can **reactivate my account if I have previously deactivated it** so that **I can return to moderating the site and manage posts again**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** that I am the site admin **when** I log back in with my credentials **then** my account is reactivated.
- [ ] **2.** **Given** that I have logged back in **when** my account is reactivated **then** I am shown a message to say my reactivation was successful.
***
**Tasks**:
- [ ] When site admin log backs in, set User.is_active = True
- [ ] Display message that confirms reactivation was successful
