### ISSUE TITLE
USER STORY: Create About Page

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#38]
As a **Site Admin** I can **create an 'About Me' page** so that **I can tell visitors of my site about me and why I have created this blog**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** that the site admin is the developer **when** on the admin panel **then** the About app is visible.
- [x] **2.** **Given** that I am on the admin panel **when** I click on the About app **then** I can create my 'About Me' page.
***
**Tasks**:
- [x] Create an 'About' app
- [X] Add the Django Quill package to the app
- [x] Create an 'about me' template page
- [x] Link the about app to the template
- [x] Ensure 'about me' template page is updated with info from the about app in the admin panel
