### ISSUE TITLE
USER STORY: View About Page

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#39]
As a **Site Admin** I can **view my 'About Me' page** so that **I can see what is being shared to others**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am the Site Admin, **when** I create my 'About Me' page  **then** I have the ability to view it on the website.
***
**Tasks**:
- [x] Check that the link for the about page works and displays the content
- [x] Update my profile in Django admin
- [x] Add necessary bootstrap styling to page
