### ISSUE TITLE
USER STORY: Update About Page

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#40]
As a **Site Admin** I can **update my 'About Me' page** so that **I can make my introduction current and relevant to visitors of the site**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** an 'About Me' page is created **when** I go to view the page in the admin panel **then** there is the option to update the information. 
- [x] **2.** **When** I click 'Save' **then** a message is shown confirming the save was successful.
***
**Tasks**:
- [x] Ensure only the latest instance is shown on the website

**Comment by mariam138** [comment]
- User story edited as the about page will be updated through the admin panel rather than on the client side, which Django admin already handles the functionality.
