### ISSUE TITLE
USER STORY: Create Comments

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#43]
As a **User** I can **comment on posts** so that **I can join in the conversation in my community**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user **when** I view a post **then** I can submit a comment.
- [x] **2.** **When** I submit my comment **then** I receive a message saying submission was successful.
- [x] **3.** **When** I have submitted my comment **then** I am shown a message that the comment is waiting to be approved.
***
**Tasks**:
- [x] Create a Comment model
- [x] Download crispyforms package
- [x] Only allow registered users to leave a comment
- [x] Tell unregistered/logged out users that they must be signed in to leave a comment
- [x] Create submit button
- [x] When submit is pressed, add comment to database
- [x] Display message that submission was successful
