### ISSUE TITLE
USER STORY: Edit Comments

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#45]
As a **User** I can **edit my comments** so that **I can edit any mistakes**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user **when** I submit a comment **then** I have the ability to edit it.
- [x] **2.** **When** I have made an edit **then** I am notified that the change was successful.
- [x] **3.** **When** editing a comment **then** I have the ability to cancel my changes before submitting.
***
**Tasks**:
- [x] Add edit button to user's comment once submitted
- [x] When edit is pressed, pre populate the form with the already made comment
- [x] Show 'Submit' button when comment is being edited
- [x] Create 'Cancel' button which appears when comment is being edited
- [x] Make sure comment isn't saved to database if 'Cancel' is clicked
- [x] Show message when edit was successful
- [x] Let comment wait for approval again if original comment made was approved
