### ISSUE TITLE
USER STORY: Delete Comments

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#46]
As a **User** I can **click 'Delete'** so that **I can delete my comments**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user **when** I have submitted a comment **then** I have the option to delete it.
- [x] **2.** **When** I click 'Delete' **then** I am asked to confirm my action.
- [x] **3.** **When** I confirm the action **then** my comment is deleted.
- [x] **4.** **When** my comment is deleted **then** I am shown a message that deletion was successful.
***
**Tasks**:
- [x] Create 'delete' button when comment has been submitted
- [x] When user presses the button, create a modal asking user to confirm action
- [x] If user confirms, delete comment from database
- [x] If comment is deleted from database, display success message to user
