### ISSUE TITLE
USER STORY: Notify User of Approved Comment

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#47]
As a **User** I can **get notifications when my comment has been approved** so that **I don't have to manually check myself**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** a user has submitted a comment, **when** the site admin approves the comment **then** the user is notified by e-mail.
- [ ] **2.** **Given** a user is logged in **when** their comment is approved **then** a message is shown on screen to notify the user.
***
**Tasks**:
- [ ] Set up an e-mail API
- [ ] Automatically send e-mail to the user when their comment is approved by admin
- [ ] Display a message on screen to the user when their comment is approved
