### ISSUE TITLE
USER STORY: Like a Blog Post

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#48]
As a **User** I can **like a blog post** so that **I can tell the author that I like their content in a simple way**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am a registered user **when** I view a post **then** the option to like the post is available.
- [ ] **2.** **When** I like the post **then** the author gets a notification
- [ ] **3.** **When** I like a post **then** it is saved into a collection called 'Likes'
***
**Tasks**:
- [ ] Add a like button to posts
- [ ] Animate/change colour of the button when pressed
- [ ] Show success message when post is liked
- [ ] Set up notifications to author when blog is liked
- [ ] Show number of likes on the blog post
