### ISSUE TITLE
USER STORY: View Liked Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#49]
As a **User** I can **view all my liked posts** so that **I can easily access them in one place**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am a registered user **when** I like a post **then** all my liked posts are stored in one place.
- [ ] **2.** **Then** I can view a paginated list of all my liked posts
***
**Tasks**:
- [ ] Create a 'liked posts' link/folder for each user
- [ ] When link is clicked, display liked posts in a paginated list
