### ISSUE TITLE
USER STORY: Add Views to Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#50]
As a **User** I can **see the number of views on my posts** so that **I can gauge how well my content is doing**.
***
**Acceptance Criteria**:
- [ ] **1.** **When** a user views a blog post, **then** the number of views that the post has had is displayed.
***
**Tasks**:
- [ ] Track number of views a post has
- [ ] Display this count on post summary
- [ ] Display this count on the full post
