### ISSUE TITLE
USER STORY: Remove Post from Likes

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#51]
As a **User** I can **remove a post from my likes** so that **I can continue my experience on the blog**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** the user is registered, **when** the like button a previously liked post is clicked **then** the post is removed from the user's liked posts
- [ ] **2.** **Then** the user is notified that the post has been removed from their likes.
***
**Tasks**:
- [ ] When like button on previously liked post is clicked again, the button changes back to its original appearance
- [ ] The post is removed from the user's liked posts
- [ ] Change number of likes on the post
