### ISSUE TITLE
USER STORY: Subscribe to an Author's Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#52]
As a **User** I can **subscribe to an Author** so that **I am always notified when that author creates a new post**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** a user is registered **when** viewing another user's profile **then** the option to subscribe to that user is available
- [ ] **2.** **When** the user clicks 'Subscribe' on the other user's profile **then** the first user will be notified to new posts from the other user.
- [ ] **3.** **Then** that other user is added to the first user's 'Subscribed' list
***
**Tasks**:
- [ ] Create 'Subscribe' button on user profile pages
- [ ] Show success message when subscribe button is clicked
- [ ] Add author to 'subscribed' list in user's profile
- [ ] Set up email notifications to user when subscribed author creates a new post
