### ISSUE TITLE
USER STORY: Unsubscribe from an Author's Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#53]
As a **User** I can **unsubscribe from an author** so that **I no longer receive notifications on new posts from them**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** the user is registered **when** the 'Unsubscribe' button is clicked **then** the user stops receiving notifications on new posts
- [ ] **2.** **Then** the author is removed from the user's 'Subscribed' list
***
**Tasks**:
- [ ] Create 'Unsubscribe' button
- [ ] Only show button if user has subscribed to author
- [ ] Stop e-mail notifications once user has unsubscribed
- [ ] Show message was unsubscribing was successful
