### ISSUE TITLE
USER STORY: Display Social Media Posts on Home Page

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#54]
As a **Site Owner** I can **link to social media posts I have made on other websites** so that **I can gain a larger following on my SNS outside of the blog and show a larger variety of content**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am a user, **when** I am visiting the homepage of the blog **then** I can see a list of social media posts from the blog owner.
- [ ] **2.** **When** I click on those posts **then** I am redirected to that post on its social media page
- [ ] **3.** **Then** I can follow the blog owner on other social media as well.
***
**Tasks**:
- [ ] Display row of instagram reels on home page
- [ ] When clicked, allow website to open instagram

**Comment by mariam138** [comment]
- Closing issue due to inability to style embedded instagram reel
- Option to create a widget of reels requires authorising an account to allow access to reels so I have decided against this and will style the homepage a different way
