### ISSUE TITLE
USER STORY: Display travel pictures on home page

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#55]
As a **Site Owner** I can **display images from my travels on my home page** so that **I can show my users visually about my travels and make the blog more interesting to interact with**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a user **when** I am on the home page **then** I can view a gallery of pictures from different countries
***
**Tasks**:
- [x] Upload pictures from travels from different countries
- [x] Display horizontally on home page
- [x] Allow user to scroll through gallery
