### ISSUE TITLE
USER STORY: Upload Pictures to Blog Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#57]
As a **User/Site Owner** I can **upload pictures to my blog posts** so that **I can make my posts more visually appealing and show pictures of my travels to other readers**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user, **when** I am creating a blog post **then** I am able to upload pictures to my post.
***
**Tasks**:
- [x] Install cloudinary package
- [x] Set up API keys for cloudinary storage
- [x] Create photo upload widget for blog posts on client side
