### ISSUE TITLE
USER STORY: Interactive Travel Map

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#58]
As a **Site Owner** I can **create an interactive travel map of the countries I have been to on my about page** so that **I can show my site users where I have been in a fun and creative way**.
***
**Acceptance Criteria**:
- [ ] **1.** **When** on the 'About' page **then** the user can see an interactive global map
- [ ] **2.** **Then** the map has pins for each place the site owner has visited
- [ ] **3.** **When** looking at the map **then** the user can zoom in and zoom out of the map
***
**Tasks**:
- [ ] Link google maps API
- [ ] Create pins/clusters for each place visited
- [ ] Add google maps widget to about home page
