### ISSUE TITLE
USER STORY: View own posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#59]
As a **User** I can **view all of the posts I have created in one place** so that **I can access them more easily rather than have to search for them**.
***
**Acceptance Criteria**:
- [x] **1.** **Given** I am a registered user **when** I am viewing my profile **then** the option to view my own posts is available as a button or link
- [x] **2.** **When** I click on the button **then** I am taken to a page which lists all of the posts I have made
***
**Tasks**:
- [x] Add 'View posts' button to user profile page
- [x] Create page template to view paginated list of user's posts
- [x] When button is clicked, user is redirected to page of their own posts

**Comment by mariam138** [comment]
- Changed story points to 2 from 4 as upon reflection, user story will require less effort to complete
