### ISSUE TITLE
USER STORY: View blog in dark mode

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#60]
As a **User** I can **switch the blog site into dark mode** so that **I can reduce the strain on my eyes and more easily read the content**.
***
**Acceptance Criteria**:
- [ ] **1.** **When** I am viewing the website **then** there is the option to toggle the website into dark mode.
- [ ] **2.** **When** I click on the toggle **then** the website changes from it's light colour theme into it's dark colour theme.
- [ ] **3.**  **When** I click on the toggle again **then** the website switches back into it's light mode.
***
**Tasks**:
- [ ] Create toggle with javascript
- [ ] Create a dark class and light class in CSS
- [ ] When toggle is pressed, the applied colour class changes
- [ ] Use bootstrap with help for toggle
