### ISSUE TITLE
USER STORY: Register for Site

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#61]
As a **User** I can **register for the site** so that **I can create my own profile, blog posts and comments.**.
***
**Acceptance Criteria**:
- [x] **1. Given** that I am an unregistered user, **when** I am on the blog's home page I can see a 'Register' button so that when I click on it, **then** I am redirected to a page to enter my details to register to the site.
- [x] **2. **When** I am logged in **then** I can no longer see the 'Register' link in the navbar.
- [x] **3.** **Then** I get a message saying my registration was successful.
***
**Tasks**:
- [x] Create a register page
- [x] Create link in navbar to direct users to register
- [x] Use the Django User model to add user profiles to the database
- [x] Hide register button once user is registered and logged in
- [x] Redirect user to homepage once registration is successful
- [x] Display success message that registration was successful on home page once redirected
