### ISSUE TITLE
USER STORY: View Profile

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#62]
As a **User** I can **view my profile** so that **I can see what information about myself I'm sharing with other blog users**.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** that I have registered for the site, **when** I click on 'View Profile' **then** I am redirected to my profile page.
- [ ] **2.** **Then** I am able to see what information has been used to create my profile upon registration.
***
**Tasks**:
- [ ] Create profile page template
- [ ] Display user's information
- [ ] Display empty fields that have not been filled in upon registration
