### ISSUE TITLE
USER STORY: Upload Profile Picture

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#63]
As a **User** I can **upload a profile picture** so that **I can give myself an identity and show others my identity**.
***
**Acceptance Criteria**:
- [X] **1.** **Given** I am a registered user, **when** I click to update my profile **then** there is the option to upload a profile picture.
- [X] **2.** **When** I click to upload a profile picture **then** I can choose one from the pictures I have saved on my laptop/tablet/phone.
- [x] **3.** **When** I have uploaded my profile picture **then** I can see it when I go back to viewing my profile.
***
**Tasks**:
- [X] Open files when 'Choose file' is clicked
- [x] When uploaded, crop picture and gravitate it towards the face using Cloudinary attributes
- [x] Display success message when image has been uploaded succesfully
- [x] Display error message if there was an issue uploading a picture
- [x] Ensure picture is stored in Cloudinary
- [x] Add cropping attributes when file is uploaded

**Comment by mariam138** [comment]
Newly created user story for uploading a picture to separate it from user story #18 .
