### ISSUE TITLE
USER STORY: Search for Posts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#64]
As a **User** I can **search for posts** so that **I can find content more relevant to me**.
***
**Acceptance Criteria**:
- [x] **1.** **When** I am navigating the site **then** there is the option to search for posts.
- [x] **2.** **When** I enter my search term and submit **then** I am shown a paginated list of posts relevant to the search term I used.
- [x] **3.** **Then** I am able to click on a blog post and get a detailed view.
***
**Tasks**:
- [x] Create search form with "GET" method
- [x] Create a template to display paginated list of results
- [x] Create url for results page
- [x] Direct user to results page when "Search" button is pressed
- [x] Create a generic list view for the search results
- [x] Create queries based off of user's search criteria
- [x] Display a message for "No results found"

**Comment by mariam138** [comment]
- Changed user story to focus only on post searching to create a separate user story for profile searching
