### ISSUE TITLE
USER STORY: Search for Profiles

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#65]
As a **User** I can **search for other people's profiles** so that **I can reach out and connect to like-minded people**.
***
**Acceptance Criteria**:
- [ ] **1.** **When** I am navigating the site **then** there is the option to search for profiles.
- [ ] **2.** **When** I enter a username or name **then** I am shown a paginated list of profiles related to the search term I used.
- [ ] **3.** **Then** I am able to click on a profile to get a detailed view.
***
**Tasks**:
- [ ] Create queries based off of user's search criteria
- [ ] Display a message for "No results found"
- [ ] Create card summaries for other user's profiles
