### ISSUE TITLE
USER STORY: View Drafts

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#66]
As a **User** I can **view my drafted posts in one place** so that **I can quickly and easily access them when I want to finish them off **.
***
**Acceptance Criteria**:
- [ ] **1.** **Given** I am a registered user **when** I am on the 'Create post' page **then** I am shown the option to select a draft to continue editing.
- [ ] **2.** **When** I click on the draft from the drop down options **then** that post is shown to me in the editor.
- [ ] **3.** **Then** I can continue editing my drafted post.
***
**Tasks**:
- [ ] Create a link to user's drafted posts on the 'Create post' page
- [ ] When clicked on, display paginated list of drafted posts
- [ ] When user clicks on one of the drafted posts, redirect back to create post page
- [ ] Using the draft instance, pre-populate the relevant fields with the already saved data
