### ISSUE TITLE
USER STORY: Create 404 Page

### ISSUE THREAD

**Issue by mariam138** [mariam138/globetrotters-gazette#67]
As a **Site Admin** I can **create my own 404 page** so that **if a user ends up on a wrong page they are notified with a 404 page error**.
***
**Acceptance Criteria**:
- [x] **1.** **When** a user reaches a non-existent page **then** they are redirected to a 404 page.
- [x] **2.** **Then** they are given the choice to go back to their previous page or to go back to the index page.
***
**Tasks**:
- [x] Create a 404 page template
- [x] Extend template from base.html
- [x] Add back button for user to return to previous page
- [x] Direct user to previous page using javascript
- [x] Add 'home' button to redirect user back to index
